### ISSUE TITLE
Random error on page load/reload: 'Cannot read property 'id' of undefined'

### ISSUE THREAD

**Issue by alecmakeus** [SquaredLabs/squaredlabs.uconn.edu#138]
I don't know what causes it but navigating to any page via the navbar resolves it pretty much every time. I can't pinpoint how to reproduce (yet), but if I had to say I think it only ever occurs on the first or second page load after `npm run dev`.

**Comment by gluxon** [comment]
I believe the bug is this function; sometimes it returns an undefined person: https://github.com/SquaredLabs/squaredlabs.uconn.edu/blob/a4f0bd2900da104122e18a68302cc6a1531bfc00/src/pages/home.vue#L137

From the looks of it, there was no hope of consistently reproducing it since some randomness was purposefully introduced.
