### ISSUE TITLE
Implement active nav link states

### ISSUE THREAD

**Issue by ColinMcNeil** [SquaredLabs/squaredlabs.uconn.edu#57]
Active nav links should be styled exactly as they are on hover: 5px Y text offset and opaque background.

**Comment by ColinMcNeil** [comment]
@gluxon Can you check out  24d747088d379e36e8fc6029ad39ed6edc866e78, particularly the changed I made to the layout. Vue kept spitting out errors about HTML elements being passed to those props.

**Comment by gluxon** [comment]
Sure thing. I'll do that now.

**Comment by ColinMcNeil** [comment]
To clarify, I made those changes to make it shut up.

**Comment by gluxon** [comment]
Ah. That's happening due to a change I forgot to make after adding the linter. (Sorry.) So we're currently treating the `vertical` and `p` props as booleans. But their implementation in some areas isn't using primitive booleans (`true` and `false`), those parts are using string booleans instead (`"true"` and `"false"`). Thus the prop type check fails.

So for one example, we have:
```html
<OurLayout
  vertical="true"
  style="margin-top: -485px">
```

The appropriate fix would be:
```html
<OurLayout
  :vertical="true"
  style="margin-top: -485px">
```

Notice the colon before vertical to get vue to interpret the template as JavaScript. I'll go ahead and push a commit to develop to fix that now.

**Comment by ColinMcNeil** [comment]
Should I amend 24d747088d379e36e8fc6029ad39ed6edc866e78 now, or is it good to merge?

**Comment by gluxon** [comment]
@ColinMcNeil I saw that you started implementing this using a custom method, but the `router-link` component does have an `active-class` prop.
