### ISSUE TITLE
Button and link initial offset does not align with background

### ISSUE THREAD

**Issue by ColinMcNeil** [SquaredLabs/squaredlabs.uconn.edu#63]
See nav links, text links, and buttons (eg "register" on Workshops page). Text baseline should align exactly with background bottom.

**Comment by ColinMcNeil** [comment]
This is what's happening:
![image](https://user-images.githubusercontent.com/5000430/40318285-1a72c42a-5cf2-11e8-98f0-6e9089186655.png)

I've been working on this one a little while. The issue is that when there is no href specified (like the rightmost links), the link is a <button>. When there is and href, they are <a>. I think the CSS is working a bit differently for the button elements. I'm not sure what the best way to fix it is. I don't want to resort to forcing it to all be <a> elements.

@gluxon any ideas?

**Comment by gluxon** [comment]
@ColinMcNeil `<a>` and `<button>` have different line heights. I forgot to reset that in the scoped `.button` class. Adding `line-height: inherit` there seems to fix it for me. I'll push that now since it's a quick one-liner.

The font of the links in the footer also changed on develop. Not sure if that was intentional, but that's something else.
